production:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
development:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
test:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
