production:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
  onesignal_app_id: 13b8935f-25b0-40a6-9d9f-85762e605d1e
  onesignal_app_key: ZTVmM2RkMmUtNzg1Yi00ZDZiLWI2NDAtYTI3ZGRjMTA1MjM5
  mailgun_api_key: 21699c6c43dfe8d16a6c8ef34e697242-9dfbeecd-14b8e9e7
  mailgun_domain: sandbox1b2dff19341149bd993659cd8c642027.mailgun.org

development:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
  onesignal_app_id: 223dd9c3-bb29-40d8-a456-94042f97c534
  onesignal_app_key: MTIzN2U2MzAtNTQ2NS00YjZlLWEwY2ItMGZhZWRiOTdlOGY5
  mailgun_api_key: 21699c6c43dfe8d16a6c8ef34e697242-9dfbeecd-14b8e9e7
  mailgun_domain: sandbox1b2dff19341149bd993659cd8c642027.mailgun.org

test:
  aws_access_key_id: AKIAICRK5CZBYORWKNCA
  aws_secret_access_key: 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
  fog_directory: gastromed-bucket
  onesignal_app_id: 223dd9c3-bb29-40d8-a456-94042f97c534
  onesignal_app_key: MTIzN2U2MzAtNTQ2NS00YjZlLWEwY2ItMGZhZWRiOTdlOGY5
  mailgun_api_key: 21699c6c43dfe8d16a6c8ef34e697242-9dfbeecd-14b8e9e7
  mailgun_domain: sandbox1b2dff19341149bd993659cd8c642027.mailgun.org
